"""many to many

Revision ID: e2deb0996b3c
Revises: 0140761cd0f7
Create Date: 2023-10-11 17:45:22.948015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2deb0996b3c'
down_revision: Union[str, None] = '0140761cd0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carsusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'cars', ['id'])
    op.drop_constraint('cars_user_id_fkey', 'cars', type_='foreignkey')
    op.drop_column('cars', 'user_id')
    op.drop_constraint('users_car_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_car_id_fkey', 'users', 'cars', ['car_id'], ['id'])
    op.add_column('cars', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cars_user_id_fkey', 'cars', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cars', type_='unique')
    op.drop_table('carsusers')
    # ### end Alembic commands ###
